apiVersion: v1
kind: Service
metadata:
  name: mcp-harga-komoditas-dan-ketahanan-pangan
spec:
  selector:
    app: smart-crawler
    kind: mcp-harga-komoditas-dan-ketahanan-pangan
  type: LoadBalancer
  externalIPs:
    - 10.11.121.38
  ports:
  - name: api
    nodePort: 30233
    port: 5200
    protocol: TCP
    targetPort: 5200
  
